<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LP-TZD-0X118172" failures="1" tests="3" name="edgeTest" time="55.901" errors="0" timestamp="2024-10-25T23:48:48 IST">
  <testcase classname="execution.TestRun" name="login" time="19.955">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="execution.TestRun" name="login" time="13.416">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="execution.TestRun" name="login" time="15.057">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at execution.TestRun.login(TestRun.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- edgeTest -->
